### PR TITLE
Add test for echo.rb

### PR DESCRIPTION
**Pull request by pknight24**
I wrote a test for echo.rb. It passed 

> rake test

sucesfully. If there is anything I need to change, please let me know.

### CODE REVIEW

**Comment by faraazahmad** [comment]
That's awesome! Just replace double quoted strings with single quoted ones when not using interpolation.

**Comment by pknight24** [comment]
Is there anything that I need to change before this is merged?

**Comment by pknight24** [comment]
Should I close the pull request?

**Comment by faraazahmad** [comment]
I'm sorry I was quiite preoccupied with other things.

**Comment by faraazahmad** [comment]
merged.

**Comment by pknight24** [comment]
No problem, thanks!

**Pull request merged**
