### PR TITLE
Pwd fix

### PR DESCRIPTION
**Pull request by pknight24**
Resolves issue #23

### CODE REVIEW

**Comment by pknight24** [comment]
closing to fix merge conflicts

**Comment by pknight24** [comment]
Is there anything I should do or change to get this merged?

**Comment by faraazahmad** [comment]
replace `args` with `params`
and create a new simple test file

**Comment by pknight24** [comment]
I changed args to params, and checked the pwd_spec, which seems to be fine. If there are any other tests I need to do, please let me know.

**Comment by faraazahmad** [comment]
NO need to `puts Dir.pwd` just return it like

`Dir.pwd`

**Comment by pknight24** [comment]
When I run it without the puts on MacOS, it does not print the working directory. Does it work for you?

**Comment by faraazahmad** [comment]
The issue has been fixed and tested to work on Mac and Linux on Travis.

**Pull request merged**
